# Generated by Django 2.2.4 on 2019-12-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIP_students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(default='static/img/logo.svg', null=True, upload_to='media/avatars'),
        ),
    ]
