# Generated by Django 2.2.4 on 2019-12-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIP_students', '0003_auto_20191202_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='../static/img/logo.svg', null=True, upload_to='media/avatars'),
        ),
    ]
