# Generated by Django 2.2.4 on 2019-12-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIP_students', '0004_auto_20191203_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_img', models.FileField(default='../static/img/logo.svg', null=True, upload_to='media/avatars')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(default='../static/img/logo.svg', null=True, upload_to='media/avatars'),
        ),
    ]
