# Generated by Django 2.2.4 on 2019-12-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIP_students', '0006_auto_20191203_2112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterImage',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='student', max_length=30),
        ),
    ]
